// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: feed.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feed (id, name, author_id, url, created_at, updated_at )
VALUES ($1, $2, $3, $4, $5, $6 ) 
RETURNING id, created_at, updated_at, name, url, author_id
`

type CreateFeedParams struct {
	ID        uuid.UUID
	Name      string
	AuthorID  uuid.UUID
	Url       string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.Name,
		arg.AuthorID,
		arg.Url,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.AuthorID,
	)
	return i, err
}
